import "~/styles/globals.css";
import { LeagueNav } from "../../_components/LeagueNav";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "SV Baseball",
  description: "Generated by IceRayer",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function LeagueLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
        <body>
            <LeagueNav />
            {children}
        </body>
  );
}