DO $$ BEGIN
 CREATE TYPE "public"."bats" AS ENUM('R', 'L', 'B');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."positions" AS ENUM('P', 'C', '1B', '2B', '3B', 'SS', 'OF', 'CI', 'MI');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."throws" AS ENUM('R', 'L', 'B');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_draft_pick" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_draft_pick_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pick_number" integer,
	"league_id" integer,
	"draft_id" integer,
	"player_id" integer,
	"team_id" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_draft_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_draft_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"league_id" integer NOT NULL,
	"draft_id" integer NOT NULL,
	"start_date" timestamp with time zone,
	"draft_type" varchar(256),
	"snake_draft" boolean DEFAULT false,
	"pick_duration" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_draft" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_draft_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"league_id" integer,
	"draft_year" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_league" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_league_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"commissioner" varchar(256),
	"co_commissioner" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_player" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_player_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"league_id" integer NOT NULL,
	"team_id" integer NOT NULL,
	"pro_id" integer NOT NULL,
	"positions" "positions",
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "playerProId" UNIQUE("pro_id","league_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256),
	"body" varchar(1024),
	"league_id" integer,
	"owner_id" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_pros" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_pros_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_number" integer,
	"player_first_name" varchar(256),
	"player_last_name" varchar(256),
	"player_name" varchar(256),
	"team" varchar(256),
	"position" "positions",
	"age" integer,
	"height" varchar(256),
	"weight" integer,
	"throws" "throws",
	"bats" "bats",
	"rank" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_queue" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_queue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"league_id" integer,
	"draft_id" integer,
	"team_id" integer,
	"player_id" integer,
	"user_id" varchar(256),
	"name" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "inQueue" UNIQUE("player_id","user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"league_id" integer NOT NULL,
	"drafts_enabled" boolean DEFAULT false,
	"name" varchar(256),
	"abbreviation" varchar(10),
	"primary_color" varchar(7),
	"secondary_color" varchar(7),
	"teams" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mildraft_team" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mildraft_team_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"league_id" integer NOT NULL,
	"owner_id" varchar(256),
	"abbreviation" varchar(5),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_draft_pick" ADD CONSTRAINT "mildraft_draft_pick_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_draft_pick" ADD CONSTRAINT "mildraft_draft_pick_draft_id_mildraft_draft_id_fk" FOREIGN KEY ("draft_id") REFERENCES "public"."mildraft_draft"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_draft_pick" ADD CONSTRAINT "mildraft_draft_pick_player_id_mildraft_pros_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."mildraft_pros"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_draft_pick" ADD CONSTRAINT "mildraft_draft_pick_team_id_mildraft_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."mildraft_team"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_draft_settings" ADD CONSTRAINT "mildraft_draft_settings_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_draft_settings" ADD CONSTRAINT "mildraft_draft_settings_draft_id_mildraft_draft_id_fk" FOREIGN KEY ("draft_id") REFERENCES "public"."mildraft_draft"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_draft" ADD CONSTRAINT "mildraft_draft_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_player" ADD CONSTRAINT "mildraft_player_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_player" ADD CONSTRAINT "mildraft_player_team_id_mildraft_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."mildraft_team"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_player" ADD CONSTRAINT "mildraft_player_pro_id_mildraft_pros_id_fk" FOREIGN KEY ("pro_id") REFERENCES "public"."mildraft_pros"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_post" ADD CONSTRAINT "mildraft_post_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_queue" ADD CONSTRAINT "mildraft_queue_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_queue" ADD CONSTRAINT "mildraft_queue_draft_id_mildraft_draft_id_fk" FOREIGN KEY ("draft_id") REFERENCES "public"."mildraft_draft"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_queue" ADD CONSTRAINT "mildraft_queue_team_id_mildraft_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."mildraft_team"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_queue" ADD CONSTRAINT "mildraft_queue_player_id_mildraft_pros_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."mildraft_pros"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_settings" ADD CONSTRAINT "mildraft_settings_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "mildraft_team" ADD CONSTRAINT "mildraft_team_league_id_mildraft_league_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."mildraft_league"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "draft_pick_idx" ON "mildraft_draft_pick" USING btree ("id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "draft_settings_idx" ON "mildraft_draft_settings" USING btree ("id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "league_idx" ON "mildraft_league" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "player_idx" ON "mildraft_player" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "mildraft_post" USING btree ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pros_idx" ON "mildraft_pros" USING btree ("id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "queue_idx" ON "mildraft_queue" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "settings_idx" ON "mildraft_settings" USING btree ("id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_idx" ON "mildraft_team" USING btree ("name");