// import css
import "~/styles/globals.css";

// import Providers
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next"

// import other
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

// import UI Components
import { TopNav } from "../_components/TopNav";
import { TimezoneSetter } from "~/_components/TimezoneSetter";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "SV Baseball",
  description: "Generated by IceRayer",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ClerkProvider>
        <body>
          <TimezoneSetter />
          <Toaster position="bottom-center" richColors />
          <TopNav />
          <main className="size-full bg-linear-to-b from-[#12026d] to-[#15162c] text-white">
            {children}
          </main>
          <Analytics />
          <SpeedInsights />
        </body>
      </ClerkProvider>
    </html>
  );
}
