import "~/styles/globals.css";

import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "SV Baseball",
  description: "Generated by IceRayer",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function TeamLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
        <div>
            {children}
        </div>
  );
}